"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "./app/src/main/"

"preserve_hierarchy": true

"files": [
  {
    "source": "res/values/strings.xml",
    "translation": "res/values-%android_code%/strings.xml",
  }
]

