"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "."

"preserve_hierarchy": true

"files": [
  {
    "source": "app/src/main/res/values/strings.xml",
    "translation": "app/src/main/res/values-%android_code%/strings.xml",
    "languages_mapping": {
      "android_code": {
        # Simplified Chinese
        "zh-CN": "zh-rCN",
        # Traditional Chinese
        "zh-TW": "zh-rTW",
      }
    }
  }
]

