"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "."

"preserve_hierarchy": true

"files": [
  {
    "source": "app/src/main/res/values/strings.xml",
    "translation": "app/src/main/res/values-%android_code%/strings.xml",
    "languages_mapping": {
      "android_code": {
        # Chinese
        "zh-CN": "zh-rCN",
        "zh-TW": "zh-rTW",
        # Portuguese
        "pt-PT": "pt",
        "pt-BR": "pt-rBR",
        # Spanish
        "es": "es",
        "es-MX": "es-rMX",
        "es-419": "es-r419",
        # English
        "en-GB": "en-rGB",
        "en-US": "en",
        "en-AU": "en-rAU",
        "en-IN": "en-rIN",
        # French
        "fr": "fr",
        "fr-CA": "fr-rCA",
        # German
        "de": "de",
        "de-AT": "de-rAT",
        "de-CH": "de-rCH",
        # Italian
        "it": "it",
        # Arabic
        "ar": "ar",
        "ar-SA": "ar-rSA",
        "ar-EG": "ar-rEG",
        # Russian
        "ru": "ru",
        # Ukrainian
        "uk": "uk",
        # Belarusian
        "be": "be",
        # Serbian
        "sr-Latn": "sr-rLatn",
        "sr-Cyrl": "sr-rCyrl",
        # Japanese
        "ja": "ja",
        # Korean
        "ko": "ko",
        # Vietnamese
        "vi": "vi",
        # Hindi
        "hi": "hi-rIN",
        # Bengali
        "bn-IN": "bn-rIN",
        "bn-BD": "bn-rBD",
        # Tamil
        "ta-IN": "ta-rIN",
        "ta-LK": "ta-rLK",
        # Telugu
        "te-IN": "te-rIN",
        # Malay
        "ms": "ms",
        "ms-MY": "ms-rMY",
        # Urdu
        "ur-IN": "ur-rIN",
        "ur-PK": "ur-rPK",
        # Turkish
        "tr": "tr",
        # Persian
        "fa": "fa",
        # Greek
        "el": "el",
        # Polish
        "pl": "pl",
        # Hungarian
        "hu": "hu",
        # Czech
        "cs": "cs",
        # Slovak
        "sk": "sk",
        # Swedish
        "sv": "sv",
        # Danish
        "da": "da",
        # Finnish
        "fi": "fi",
        # Dutch
        "nl": "nl",
        # Thai
        "th": "th-rTH",
        # Khmer
        "km": "km-rKH",
        # Lao
        "lo": "lo-rLA",
        # Filipino
        "fil": "fil",
        "fil-PH": "fil-rPH",
        # Indonesian
        "id": "id",
        "id-ID": "id-rID",
        # Burmese
        "my": "my-rMM",
        # Kazakh
        "kk": "kk-rKZ",
        # Uzbek
        "uz": "uz-rUZ"
      }
    }
  }
]

